### ISSUE TITLE
Scrollbar visible in Bing directions page

### ISSUE THREAD

**Issue by omkarambre** [synergy-cms/JSP-Store-Locator#4]
Scrollbar visible in Bing directions page. Need to hide or remove it somehow.
![scrollbar](https://cloud.githubusercontent.com/assets/9278799/20217493/2bfb05a2-a846-11e6-9b3f-408767a5ab52.png)

**Comment by shrastibansal** [comment]
comment the line/_overflow:auto;_/ at line 218 in style_bing.css

**Comment by omkarambre** [comment]
Issue fixed in http://localhost/joomla_bug_fixes
